default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>
  username: "<%= ENV["DATABASE_USER"] if ENV["DATABASE_USER"] %>"
  password: "<%= ENV["DATABASE_PASSWORD"] if ENV["DATABASE_PASSWORD"].present? %>"
  url: <%= ENV["DATABASE_URL"] %>
  aws_rds_iam_auth_token_generator: 'default'

development:
  primary:
    <<: *default
    database: work_requirements_self_advocacy_tool_development
  queue:
    <<: *default
    database: work_requirements_self_advocacy_tool_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: work_requirements_self_advocacy_tool_test

staging:
  primary:
    <<: *default
    database: work_requirements_self_advocacy_tool_staging
  cache:
    <<: *default
    database: work_requirements_self_advocacy_tool_staging_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: work_requirements_self_advocacy_tool_staging_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: work_requirements_self_advocacy_tool_staging_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: work_requirements_self_advocacy_tool_production
  cache:
    <<: *default
    database: work_requirements_self_advocacy_tool_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: work_requirements_self_advocacy_tool_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: work_requirements_self_advocacy_tool_production_cable
    migrations_paths: db/cable_migrate
