default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("RAILS_DB_PORT", "5432") if ENV.fetch("RAILS_DB_PORT", "5432") %>
  host: <%= ENV.fetch("RAILS_DB_HOST", "localhost") if ENV.fetch("RAILS_DB_HOST", "localhost") %>
  username: <%= ENV["RAILS_DB_USERNAME"] if ENV["RAILS_DB_USERNAME"] %>
  password: <%= ENV["RAILS_DB_PASSWORD"] if ENV["RAILS_DB_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  primary:
    <<: *default
    database: work_requirements_self_advocacy_tool_development
  queue:
    <<: *default
    database: work_requirements_self_advocacy_tool_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: work_requirements_self_advocacy_tool_test

deploy_default: &deploy_default
  <<: *default
  host: "<%= ENV["DATABASE_HOST"] if ENV["DATABASE_HOST"] %>"
  username: "<%= ENV["DATABASE_USER"] if ENV["DATABASE_USER"] %>"
  password: "<%= ENV["DATABASE_PASSWORD"] if ENV["DATABASE_PASSWORD"] %>"

staging:
  primary:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_staging
  cache:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_staging_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_staging_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_staging_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_production
  cache:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *deploy_default
    database: work_requirements_self_advocacy_tool_production_cable
    migrations_paths: db/cable_migrate