name: Deploy to staging from main

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to staging
    permissions:
      checks: write
      contents: write
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
      infra_branch: main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEPLOYMENT_APP_ID: ${{ secrets.DEPLOYMENT_APP_ID }}
      DEPLOYMENT_APP_KEY: ${{ secrets.DEPLOYMENT_APP_KEY }}
